
 #  - terraform -chdir=./2-EBS/1-EBS-addon-terraform/ init
 # terraform -chdir=./2-EBS/1-EBS-addon-terraform/ apply -auto-approve

version: 0.2

phases:

  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/1.4.0-alpha20221207/terraform_1.4.0-alpha20221207_linux_amd64.zip"
      - "unzip terraform_1.4.0-alpha20221207_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - cd EKS-Terraform-Pipeline-CodeBuild/4-EKS-Cluster-Autoscaler/2-cluster-autoscaler-sample-app/
      - cat c1-versions.tf
      - terraform version
      - terraform init
      - terraform plan
      
  build:
    commands:
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo terraform completed on `date`
